name: procgen
description: A collection of procedural generation algorithms.
version: 1.0.0
repository: https://github.com/bramp/procgen

environment:
  sdk: ^3.3.3

dependencies:
  collection: ^1.18.0
  delaunay: ^2.0.0
  meta: ^1.11.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
